name: Snazzy LookML Linter 
author: 
description: Lint LookML Projects and create Pull Request reviews with linting violations.

inputs:
  configFile: # id of input
    description: "path to lookml project"
    required: true
    default: ${{ github.workspace }}/.github/workflows/config.example.yaml
  lookMlProject: # directory containing files
    description: "path to lookml files"
    required: false


runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.configFile }}
    - ${{ inputs.lookMlProject }}

