name: Snazzy LookML Linter 
author: 
description: Lint LookML Projects and create Pull Request reviews with linting violations.

inputs:
  failIf:
    description: Fail if *any* violations are detected or only *new* ones (valid values are "new" or "any")
    required: false
    default: new
  args:
    description: None
    required: false
    default: 

runs:
  using: docker
  image: Dockerfile

branding:
  icon: code
  color: gray-dark
