- rule: field_should_have_description
  severity: error
- rule: dimension_should_have_x
  severity: ignore
- rule: measure_should_have_y
  severity: ignore
- rule: view_should_have_z
  severity: warning
- rule: view_requires_abc
  severity: ignore
- rule: view_requires_xyz
  severity: ignore
